src/modules/menu/models/MenuItem.php
<?php

namespace quoma\core\modules\menu\models;

use quoma\core\helpers\ClassFinderHelper;
use quoma\core\modules\menu\components\MenuItemFactory;
use quoma\core\modules\menu\MenuModule;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "menu_item".
 *
 * @property integer $menu_item_id
 * @property string $label
 * @property string $url
 * @property string $class
 * @property integer $left
 * @property integer $rigth
 * @property integer $menu_id
 * @property integer $parent_id
 * @property string target
 *
 * @property Menu $menu
 * @property MenuItem $parent
 * @property MenuItem[] $menuItems
 */
class MenuItem extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'menu_item';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['label', 'url', 'class',  'menu_id'], 'required'],
            [['left', 'rigth', 'target'], 'safe'],
            [['left', 'rigth', 'menu_id', 'parent_id'], 'integer'],
            [['label', 'target'], 'string', 'max' => 45],
            [['url', 'class'], 'string', 'max' => 255],
            [['menu_id'], 'exist', 'skipOnError' => true, 'targetClass' => Menu::className(), 'targetAttribute' => ['menu_id' => 'menu_id']],
            [['parent_id'], 'exist', 'skipOnError' => true, 'targetClass' => MenuItem::className(), 'targetAttribute' => ['parent_id' => 'menu_item_id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'menu_item_id' => 'Menu Item ID',
            'label' => 'Label',
            'url' => 'Url',
            'class' => 'Class',
            'left' => 'Left',
            'rigth' => 'Rigth',
            'menu_id' => 'Menu ID',
            'parent_id' => 'Parent ID',
            'target' => 'Target',
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getMenu()
    {
        return $this->hasOne(Menu::className(), ['menu_id' => 'menu_id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getParent()
    {
        return $this->hasOne(MenuItem::className(), ['menu_item_id' => 'parent_id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getMenuItems()
    {
        return $this->hasMany(MenuItem::className(), ['parent_id' => 'menu_item_id']);
    }
       
    public function getChildren(){
        
        return MenuItemFactory::findAllInstance(['parent_id' => $this->menu_item_id]);
    }
    public function loadData($item){
        $this->menu_item_id = $item->menu_item_id;
        $this->label = $item->label;
        $this->url = $item->url;
        $this->class = $item->class;
        $this->left = $item->left;
        $this->rigth = $item->rigth;
        $this->parent_id = $item->parent_id;
        $this->menu_id = $item->menu_id;
        $this->target= $item->target;
    }
    
    public static function getTypes(){
        
        $items_paths = array_merge(MenuModule::getInstance()->defaultItemsPath, MenuModule::getInstance()->itemsPaths);
        \Yii::info($items_paths);
        $classes= ClassFinderHelper::findClasses($items_paths, true, true, [MenuItem::className()]);
        $types= [];
        \Yii::info($classes);
        foreach ($classes as $class){

            $types[] = [
                'class' => $class,
                'view' => $class::$form,
                'name' => $class::typeName(),
                'child' => $class::canBeChild(),
                'children' => $class::hasChildren(),
            ];

        }

        return $types;
    }
    
     /**
     * Funcion para armar preorder (Modified Preorder Tree Traversal)
     */
    public static function preorderTree($menu_id, $nodes = null, $lft = 1)
    {
        
        if($nodes === null){
            $nodes = self::find()->where('parent_id IS NULL')->andWhere(['menu_id' => $menu_id])->orderBy(['menu_item_id' => SORT_ASC])->all();
        }
        
        $rgt= $lft + 1;
        
        error_log(print_r($nodes,1));
        
        
        foreach($nodes as $node){
            if($node->getChildren()->exists()){
                $children= $node->getChildren()->all();
                $rgt = self::preorderTree($children, $rgt);
            }else{
                $rgt = $lft + 1;
            }
            
            $node->updateAttributes([
                'left' => $lft,
                'rigth' => $rgt
            ]);
            $lft = $rgt+1;
        }
        
        return $rgt+1;
        
    }
    
    /**
     * Antes de eliminar borro las relaciones con los hijos
     * @return boolean
     */
    public function beforeDelete() {
        parent::beforeDelete();
        if(!empty($this->menuItems)){
            foreach ($this->menuItems as $item){
                $item->delete();
            }
        }
        
        return true;
    }
    
    /**
     * Valida si la clase del item es valida
     * @param type $class
     * @return boolean
     */
    public static function validateClass($class){
                
        if (class_exists($class)) {
            return true;
        }else{
            return false;
        }
    }

    /**
     * @param $item
     * @param $menu_id
     * @param null $parent
     * @return bool
     */
    public static function create($item, $menu_id, $parent = null){
        $instance= new self();

        $instance->label= $item['label'];
        $instance->class= self::className();
        $instance->url= $item['url'];
        $instance->parent_id = $parent;
        $instance->menu_id= $menu_id;
        $instance->target= $item['target'];

        if ($instance->save(false)) {
            if (isset($item['children'])) {
                foreach ($item['children'] as $i){
                    if(MenuItem::validateClass($i['class'])){
                        $i['class']::create($i, $menu_id, $instance->menu_item_id);
                    }
                }
            }
            return true;
        }else{
            error_log(print_r($instance->getErrors()),1);
            return false;
        }


    }

    /**
     * Si la clase actual puede ser hija en un dropdown
     * @return bool
     */
    public static function canBeChild(){
        return true;
    }

    /**
     * Implementación base: cada tipo de item debe implementar esta función
     * @return string
     */
    public function createUrl(){
        return $this->url;
    }

    /**
     * @return mixed
     */
    public function getClassLabel(){
        return static::typeName();
    }

    /**
     * @deprecated
     *
     * Renderiza el item para el frontend
     * @return string
     */
    public function renderItem($position, $parent_pos= '', $item_class= null, $anchor_class= null, $child_class= null){
        $target = $this->target == '_blank' ? ' target="_blank"' : '';
        if(count($this->children) > 0){

            $item= '<li class="'.$item_class.' dropdown">'
                . '<a class ="'.$anchor_class.' dropdown-toggle" href="'.$this->createUrl().'"'
                . ' data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"'. $target .'>'.$this->label.'</a>';

            $item .= '<ul class="dropdown-menu dropdown-menu-right">';
            foreach ($this->children as $key => $child){
                $item.= $child->renderItem(($key + 1), $position, $child_class, $anchor_class);
            }
            $item.= '</ul>';
        }else{
            $item= '<li class="'.$item_class.'" ><a class ="'.$anchor_class.'" href="'.$this->createUrl().'"'. $target. '>'.$this->label.'</a>';

        }

        $item.= '</li>';

        return $item;
    }


}

src/modules/menu/controllers/MenuController.php
<?php

namespace quoma\core\modules\menu\controllers;

use quoma\core\modules\menu\MenuModule;
use Yii;
use quoma\core\modules\menu\models\Menu;
use quoma\core\modules\menu\models\search\MenuSearch;
use quoma\core\modules\menu\components\Controller as ModuleController;
use yii\helpers\ArrayHelper;
use yii\web\BadRequestHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MenuController implements the CRUD actions for Menu model.
 */
class MenuController extends ModuleController
{

    /**
     * Lists all Menu models.
     * @return mixed
     */
    public function actionIndex($site_id= null)
    {
        if (MenuModule::getInstance()->multisite && MenuModule::getInstance()->site_required && empty($site_id)){
            throw new BadRequestHttpException('site_id is required');
        }

        if (MenuModule::getInstance()->multisite && MenuModule::getInstance()->site_required){
            $this->setWebsite($site_id);
        }
        $searchModel = new MenuSearch();
        $searchModel->site_id= $site_id;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);


        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Menu model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id, $site_id= null)
    {
        if (MenuModule::getInstance()->multisite && MenuModule::getInstance()->site_required && empty($site_id)){
            throw new BadRequestHttpException('site_id is required');
        }

        if (MenuModule::getInstance()->multisite && MenuModule::getInstance()->site_required){
            $this->setWebsite($site_id);
        }

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Menu model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($site_id= null)
    {
        if (MenuModule::getInstance()->multisite && empty($site_id)){
            throw new BadRequestHttpException('site_id is required');
        }

        if (MenuModule::getInstance()->multisite){
            $this->setWebsite($site_id);
        }

        $model = new Menu();
        $model->site_id= $site_id;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->menu_id, 'site_id' => $site_id]);
        } else {
            $item_types= \quoma\core\modules\menu\models\MenuItem::getTypes();
            return $this->render('create', [
                'model' => $model,
                'item_types' => $item_types,
            ]);
        }
    }

    /**
     * Updates an existing Menu model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id, $site_id = null)
    {

        if (MenuModule::getInstance()->multisite && MenuModule::getInstance()->site_required && empty($site_id)){
            throw new BadRequestHttpException('site_id is required');
        }

        if (MenuModule::getInstance()->multisite && MenuModule::getInstance()->site_required){
            $this->setWebsite($site_id);
        }

        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            // Debido a que no siempre se modifican los atributos del modelo en cuestion, el evento afterSave no se dispara siempre al actualizar
            // y existe la posibilidad de que los cambios en los items no se salven
            // Para saber si se salvaron los items uso el atributo _saveItems, que vendra en true si se disparo el afterSave,
            //  de lo contrario hay que salvar los items
            if (!$model->_saveItems) {
                $model->saveItems();
            }
            Yii::$app->session->addFlash('success', Yii::t('app','Menu saved successfully!'));
            return $this->redirect([MenuModule::getInstance()->redirect_view, 'id' => $model->menu_id, 'site_id' => $site_id]);
        } else {
            $item_types= \quoma\core\modules\menu\models\MenuItem::getTypes();
            return $this->render('update', [
                'model' => $model,
                'item_types' => $item_types,
            ]);
        }
    }

    /**
     * Deletes an existing Menu model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $site_id = $model->site_id;
        $model->delete();

        return $this->redirect(['index', 'site_id' => $site_id]);
    }

    /**
     * Finds the Menu model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Menu the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Menu::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    /**
     * Devuelve por ajax el formulario de item solicitado por view
     * @param type $view
     * @return type
     */
    public function actionItemForm($view){
        if (\Yii::$app->request->isAjax) {
            $form = $this->renderAjax($view);
            
            \Yii::$app->response->format= \yii\web\Response::FORMAT_JSON;
            
            return ['status'=> 'success', 'form' => $form];
        }
    }

    
    public function actionClone($id, $site_id = null){

        if (MenuModule::getInstance()->multisite){
            $this->setWebsite($site_id);
        }
        
        $clone= new Menu();
        
        if ($clone->load(Yii::$app->request->post()) && $clone->save()) {
            return $this->redirect(['view', 'id' => $clone->menu_id]);
        }else{
            $originMenu= $this->findModel($id);
            $item_types= \quoma\core\modules\menu\models\MenuItem::getTypes();
            return $this->render('clone', ['clone'=> $clone, 'origin' => $originMenu, 'item_types' => $item_types]);
        }
        
    }
}

src/modules/menu/views/menu/_form.php
<?php
use yii\bootstrap\ActiveForm;

\quoma\core\assets\bootbox\BootboxAsset::register($this);
\yii\jui\JuiAsset::register($this);
?>

<style>
    .menu_item {

        min-height: 50px;
        margin-bottom: 5px;
        float: left;

    }

    .sub-menu{
        text-align: right;
        padding-bottom: 10px ;
        padding-top: 5px;

    }

    .sub-menu > .menu_item{
        position: relative;
        float: right;
        width: 97%;
        min-height: 0;
        border: none;
    }

    .menu-preview {
        list-style: none;
        padding-bottom: 15px;
        width: 100%;
    }
    .input-group-addon{
        border-bottom-left-radius: 0 0;
    }

    .dropdown-link {
        min-height: 100px;
        background-color: white;
    }


</style>

<div class="menu_form">

    <?php $form = ActiveForm::begin(['id' => 'menu-create-form']); ?>
    <div class="row no-margin-sides">

        <div class="col-lg-4 col-md-4">
            <div class="panel panel-default">
                <div class="panel-body">

                    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>


                    <?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title"><?php echo Yii::t('app','Item Types')?></h4>
                        </div>
                        <div class="panel-body">

                            <div class="item_types" style="text-align: center">
                                <ul style="list-style: none">
                                    <?php foreach ($item_types as $type):?>
                                        <li>
                                            <?php echo \yii\bootstrap\Html::button('<span class="glyphicon glyphicon-plus"></span> '. Yii::t('app','Add'). ' '.$type['name'], [
                                                'class' => 'btn btn-default link_type',
                                                'data' => [
                                                    'view' => $type['view'],
                                                    'class' => $type['class'],
                                                    'parent' => '#'
                                                ],
                                                'style' => 'margin-bottom:20px; width:100%;'
                                            ])?>
                                        </li>
                                    <?php endforeach;?>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <?php echo \yii\helpers\Html::submitButton(Yii::t('app','Save'), ['class' => 'btn btn-primary'])?>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-lg-8 col-md-8">
            <div class="well">
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="menu-preview sort-list">
                            <?php foreach ($model->children as $key => $item):?>
                                    <?php echo $this->render('_item', ['key' => $key, 'item' => $item, 'item_types' => $item_types])?>
                            <?php endforeach;?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <?php \yii\bootstrap\ActiveForm::end()?>

</div>

<script>

    var MenuForm= new function(){

        this.parent = undefined;
        this.init= function(){
            $(document).on('click', '.link_type', function(e){
                e.preventDefault();
                MenuForm.parent= $(this).data('parent');
                console.log(MenuForm.parent);
                $.ajax({
                    url: "<?php echo \yii\helpers\Url::to(['/menu/menu/item-form'])?>",
                    data: $.param({view: $(this).data('view')}),
                    dataType: 'json',
                    success: function(response){
                        if(response.status === 'success'){
                            bootbox.dialog({
                                title: "<?php echo Yii::t('app', 'Add Item')?>",
                                message: response.form,
                            })
                        }
                    }
                })
            })

            $('.menu-preview').on('click', '.btn-rmv', function(e){
                e.preventDefault();
                var item = $(this).closest('.menu_item');
                if($(this).closest('.menu_item').find('.sub-menu li').length > 0){
                    bootbox.confirm('<?php echo Yii::t('app','Are you sure to eliminate the item')?> ' + $(item).find('.item-label-input').val(), function(result){
                        if (result){
                            $(item).remove();
                        }
                    })
                }else{
                    $(item).remove();
                }
            })

            MenuForm.createSortables();
        }

        this.addItem= function(label, url, target, link_class, typeName, child){
            var position = MenuForm.parent === '#' ? $('.menu-preview li').length : $('#sub-'+ MenuForm.parent + ' li').length;
            console.log(position);

            var item= MenuForm.render(label, url, target, MenuForm.parent, position, link_class, typeName, child);

            if (MenuForm.parent === '#'){
                $('.menu-preview').append(item);
            }else{
                $('#sub-'+ MenuForm.parent).append(item);
            }
        }

        this.render= function(label, url, target, parent, position, link_class, typeName, child) {
            var pos= parent === '#' ? '['+ position + ']' : '['+parent+'][children]['+ position + ']';

            if(parent === '#' && child) {
                var item = '<li class="menu_item dropdown-link" id="i' + position + '" data-type_name="' + typeName + '" data-children=' + child + '> ';
            }else{
                var item = '<li class="menu_item" id="i' + position + '" data-type_name="' + typeName + '" data-children=' + child + '> ';

            }
            item = item + '<div class="input-group">'+
                              '<span class="input-group-addon"><span class="glyphicon glyphicon-move"></span></span>'+
                              '<span class="input-group-addon">'+typeName+'</span>';

            item= item + '<input type="input" name="Menu[items]'+pos+'[label]" class="form-control item-label-input" value="'+label+'">';

            item = item + '<span class="input-group-btn">';
            console.log(child);
            if(parent === '#' && child){

                item = item +'  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">'+
                '<span class="glyphicon glyphicon-plus"></span>'+
               '</button>'+
                '<ul class="dropdown-menu dropdown-menu-right">'+
                    <?php foreach ($item_types as $type):?>
                        <?php if ($type['child']):?>
                            '<li><a href="#" class="link_type" data-view="<?php echo $type['view']?>" data-parent="'+position+'" data-class="<?php echo addslashes($type['class'])?>"><?php echo Yii::t('app','Add'). ' '.$type['name']?></a></li>'+
                        <?php endif;?>
                    <?php endforeach;?>
                '</ul>';
            }
            item = item + ' <button type="button" class="btn btn-default btn-rmv"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>';


            item = item + '</span></div>';

            item= item + '<input type="hidden" name="Menu[items]'+pos+'[url]" class="item-url-input" value="'+url+'">'+
                    '<input type="hidden" name="Menu[items]'+pos+'[target]" class="item-target-input" value="'+target+'">'+
                    '<input type="hidden" name="Menu[items]'+pos+'[class]" class="item-class-input" value="'+link_class+'">';



            if(parent === '#' && child){
                item  = item + '<ul id="sub-'+position+'" class="sub-menu sort-list"></ul>';
            }

            item = item + '</li>';

            return item;
        }

        this.createSortables= function(){
            $('.menu-preview').sortable({
                dropOnEmpty: true,
                connectWith: '.sort-list',
                opacity: 0.5,
                update: function(event, ui){
                    MenuForm.refresh();
                    MenuForm.afterSort();
                    MenuForm.createSortables()
                }
            });

            $('.sub-menu').sortable({
                dropOnEmpty: true,
                connectWith: '.sort-list',
                opacity: 0.5,
                update: function(event, ui){
                    MenuForm.refresh();
                    MenuForm.afterSort();
                    MenuForm.createSortables()
                }
            });
        }

        this.afterSort= function(){
            $.each($('.menu-preview').children('.menu_item'), function(i, o){
                $(o).find('.item-label-input').attr('name', 'Menu[items]['+i+'][label]');
                $(o).find('.item-url-input').attr('name', 'Menu[items]['+i+'][url]');
                $(o).find('.item-target-input').attr('name', 'Menu[items]['+i+'][target]');
                $(o).find('.item-class-input').attr('name', 'Menu[items]['+i+'][class]');

                $.each($(o).find('.sub-menu').children('.menu_item'), function(j, sub){
                    $(sub).find('.item-label-input').attr('name', 'Menu[items]['+i+'][children]['+j+'][label]');
                    $(sub).find('.item-url-input').attr('name', 'Menu[items]['+i+'][children]['+j+'][url]');
                    $(sub).find('.item-target-input').attr('name', 'Menu[items]['+i+'][children]['+j+'][target]');
                    $(sub).find('.item-class-input').attr('name', 'Menu[items]['+i+'][children]['+j+'][class]');
                })

            })
        }

        this.refresh= function(){
            $.each($('.menu-preview').children('.menu_item'), function(i, o){
                var label = $(o).find('.item-label-input').val();
                var url = $(o).find('.item-url-input').val();
                var target = $(o).find('.item-target-input').val();
                var link_class = $(o).find('.item-class-input').val();
                var typeName= $(o).data('type_name');
                var has_children= $(o).data('children');
                var children= new Array();

                $.each($(o).find('.sub-menu').children('.menu_item'), function(j, sub){
                    var sub_label= $(sub).find('.item-label-input').val();
                    var sub_url= $(sub).find('.item-url-input').val();
                    var sub_target= $(sub).find('.item-target-input').val();
                    var sub_link_class= $(sub).find('.item-class-input').val();
                    var sub_typeName= $(sub).data('type_name');
                    var sub_has_children= $(sub).data('children');

                    children.push(MenuForm.render(sub_label, sub_url, sub_target, i, j, sub_link_class, sub_typeName, sub_has_children));
                });

                var new_item= MenuForm.render(label, url, target, '#', i, link_class, typeName, has_children);

                $(o).replaceWith(new_item);
                $.each(children, function (k, ch) {
                        $('#i'+ i).find('.sub-menu').append($(ch));
                });
            });
        }

    }



</script>

<?php $this->registerJs('MenuForm.init()')?>

src/modules/menu/views/menu/_item.php
<?php
/**
 * Created by PhpStorm.
 * User: juan
 * Date: 16/05/18
 * Time: 14:56
 */
?>

<li class="menu_item <?php echo $item->children ? 'dropdown-link' : ''?>" data-type_name="<?php echo $item->classLabel?>" data-children=<?php echo $item->children ? 1 : 0?>>


    <div class="input-group">
        <span class="input-group-addon"><span class="glyphicon glyphicon-move"></span></span>
        <span class="input-group-addon"><?php echo $item->classLabel?></span>
        <?php echo \yii\bootstrap\Html::textInput('Menu[items]['.$key.'][label]', $item->label, ['class' => 'form-control item-label-input' ])?>
        <span class="input-group-btn">
            <?php if($item->children):?>
                <button type="button" class="btn btn-default   dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
                <ul class="dropdown-menu dropdown-menu-right">
                    <?php foreach ($item_types as $type):?>
                        <?php if ($type['child']):?>
                            <li><a href="#" class="link_type" data-view="<?php echo $type['view']?>" data-parent="<?php echo $key?>" data-class="<?php echo addslashes($type['class'])?>"><?php echo Yii::t('app','Add'). ' '.$type['name']?></a></li>
                        <?php endif;?>
                    <?php endforeach;?>
                </ul>
             <?php endif;?>
            <button type="button" class="btn btn-default btn-rmv"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
        </span>
    </div>


    <input type="hidden" name="Menu[items][<?php echo $key?>][url]" class="item-url-input" value="<?php echo $item->url?>">
    <input type="hidden" name="Menu[items][<?php echo $key?>][target]" class="item-target-input" value="<?php echo $item->target?>">
    <input type="hidden" name="Menu[items][<?php echo $key?>][class]" class="item-class-input" value="<?php echo $item->class?>">

    <ul id="sub-<?= $key ?>" class="sub-menu sort-list">
        <?php foreach ($item->children as $j => $child):?>
            <li class="menu_item" data-type_name="<?php echo $child->classLabel?>" data-children=0>
                <div class="input-group">
                    <span class="input-group-addon"><span class="glyphicon glyphicon-move"></span></span>
                    <span class="input-group-addon"><?php echo $child->classLabel?></span>
                    <?php echo \yii\bootstrap\Html::textInput('Menu[items]['.$key.'][children]['.$j.'][label]', $child->label, ['class' => 'form-control item-label-input' ])?>
                        <span class="input-group-btn">
                            <button type="button" class="btn btn-default btn-rmv"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
                        </span>
                </div>


                <input type="hidden" name="Menu[items][<?php echo $key?>][children][<?php echo $j ?>][url]" class="item-url-input" value="<?php echo $child->url?>">
                <input type="hidden" name="Menu[items][<?php echo $key?>][children][<?php echo $j ?>][target]" class="item-target-input" value="<?php echo $child->target?>">
                <input type="hidden" name="Menu[items][<?php echo $key?>][children][<?php echo $j ?>][class]" class="item-class-input" value="<?php echo $child->class?>">
            </li>
        <?php endforeach;?>
    </ul>

</li>

src/modules/menu/views/menu/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\modules\menu\models\search\MenuSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="menu-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'menu_id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'slug') ?>

    <?= $form->field($model, 'description') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

src/modules/menu/views/menu/clone.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model quoma\core\modules\menu\models\Menu */

$this->title = 'Clone Menu: '. $origin->name;
$this->params['breadcrumbs'][] = ['label' => 'Menus', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="menu-clone">
    <?php if (\quoma\core\modules\menu\MenuModule::getInstance()->show_view_title):?>
        <h1><?php echo $this->title?></h1>
    <?php endif;?>
    <?= $this->render('_form', [
        'model' => $origin,
        'item_types' => $item_types,
        'origin' => $origin    
    ]) ?>

</div>

src/modules/menu/views/menu/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model quoma\core\modules\menu\models\Menu */

$this->title = 'Create Menu';
$this->params['breadcrumbs'][] = ['label' => 'Menus', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="menu-create">

    <?php if (\quoma\core\modules\menu\MenuModule::getInstance()->show_view_title):?>
        <h1><?php echo $this->title?></h1>
    <?php endif;?>

    <?= $this->render('_form', [
        'model' => $model,
        'item_types' => $item_types
    ]) ?>

</div>